apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hackathon-todo

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - redis-deployment.yaml
  - backend-deployment.yaml
  - reminder-deployment.yaml
  - frontend-deployment.yaml
  - dapr-components.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: hackathon-todo
